### ISSUE TITLE
unable to initialize

### ISSUE THREAD

**Issue by tstellanova** [martindeegan/rust_pigpio#7]
I've got `pigpiod` running on RPi3. I'm able to run python samples that access pigpiod as the `pi` user. However, when I try to build and run the rust_pigpio samples I get the following error:

```
pi@rpi3-red01:~/Documents/proj/rust_pigpio $ cargo run --example light
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/light`
2018-02-12 21:06:00 initCheckPermitted: 
+---------------------------------------------------------+
|Sorry, you don't have permission to run this program.    |
|Try running as root, e.g. precede the command with sudo. |
+---------------------------------------------------------+


thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Initialize failed"', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:57
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:577
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:772
  11: light::main
             at examples/light.rs:9
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:101
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:365
             at /checkout/src/libstd/rt.rs:58
  14: main
  15: __libc_start_main
```
I'm guessing this is a simple misconfiguration -- any suggestions appreciated!

**Comment by martindeegan** [comment]
Hey, first of all, pigpiod isn't needed. This library wraps the C lib. To fix your problem, you just have to run with root. I'm not sure if they added `sudo cargo run` so you will probably have to run the executable in the target directory.

**Comment by tstellanova** [comment]
Thanks for the clarification -- we'll switch to a wrapper that uses pigpiod.
